### ISSUE TITLE
Token Streaming in only returns first token correctly.

### ISSUE THREAD

**Issue by gbuuu** [microsoft/onnxruntime-genai#1087] opened 2024-11-21 19:31 UTC
I successfully quantized the mistralai/Mistral-Nemo-Instruct-2407 model to ONNX using the following command:

`python awq-quantized-model.py --model_path mistralai/Mistral-Nemo-Instruct-2407 --quant_path ./mistralai/mistral-nemo-instruct-2407-awq/ --output_path ./mistralai/mistral-nemo-instruct-2407-awq-onnx/ --execution_provider cuda`

I tested the ONNX model in Python, and it works without any issues. When testing in C#, I can generate the complete output. However, when trying to use streaming to retrieve tokens one by one, only the first token is returned correctly. All subsequent tokens return 0 in the loop.

```
using Microsoft.ML.OnnxRuntimeGenAI;

using Model model = new Model(@"mistral-nemo-instruct-awq-onnx");
using Tokenizer tokenizer = new Tokenizer(model);

var inputs = tokenizer.Encode($"<s>[INST]Hello[/INST]</s>");
var generatorParams = new GeneratorParams(model);

generatorParams.SetSearchOption("min_length", 10);
generatorParams.SetSearchOption("max_length", 2048);
generatorParams.SetInputSequences(inputs);

//var outputSequences = model.Generate(generatorParams);
//var outputString = tokenizer.Decode(outputSequences[0]);

using var tokenizerStream = tokenizer.CreateStream();
using var generator = new Generator(model, generatorParams);

while (!generator.IsDone())
{
    generator.ComputeLogits();
    generator.GenerateNextToken();

    Console.Write(tokenizerStream.Decode(generator.GetSequence(0)[^1]));
}
```

Any suggestions or workarounds for resolving this issue in C# would be appreciated.

Thanks.

 - OS: [Windows 11]
 - Cuda 12.4, Cudnn 9
 - Version: NuGet [Microsoft.ML.OnnxRuntimeGenAI.Cuda - 0.5.1] [Microsoft.ML.OnnxRuntime.Gpu - 1.20.1]

**Comment by skyline75489** [comment] 2024-11-25 03:18
Hi Thanks for the feedback! Can you also post your python script that works?

**Comment by ambroser53** [comment] 2024-11-25 19:11
+1 this is happening to me too but with option 2 in the [HelloPhi example](https://github.com/microsoft/onnxruntime-genai/tree/main/examples/csharp/HelloPhi)

**Comment by baijumeswani** [comment] 2024-11-25 23:54
I am able to reproduce this issue even with C++. It seems like a problem that was introduced in this PR: https://github.com/microsoft/onnxruntime-genai/pull/973

But I still need to evaluate further.

**Comment by baijumeswani** [comment] 2024-12-20 22:21
I tried this again today using main. I was not able to reproduce the issue. It would appear that some change went in that resolved the issue.

In our next release (0.6.0) which we will release in early Jan, this issue should be resolved.

I'll close the issue now. Please let me know if you have more questions or concerns.

**Closed by baijumeswani** 2024-12-20 22:21 UTC

**Comment by cmonto** [comment] 2025-01-12 20:23
Still waiting for 0.6.0.. below versions not working. Also I see that my rtx 4060 is not being used at all even though have the following:

<PackageReference Include="Microsoft.ML.OnnxRuntime.Gpu" Version="1.20.1" />
<PackageReference Include="Microsoft.ML.OnnxRuntimeGenAI.Cuda" Version="0.5.2" />

`using Config config = new Config(modelPath);
config.ClearProviders();

string executionProvider = modelPath.Contains("cuda") || modelPath.Contains("gpu") ? "cuda" : "cpu";

if (executionProvider != "cpu")
{
    config.AppendProvider(executionProvider);
    if (executionProvider == "cuda")
    {
        config.SetProviderOption(executionProvider, "enable_cuda_graph", "0");
    }
}

using var model = new Model(config);
using var tokenizer = new Tokenizer(model);`
