### ISSUE TITLE
Can't use this lib and the non-genai version of the onnxruntime in the same MSIX project.

### ISSUE THREAD

**Issue by azchohfi** [microsoft/onnxruntime-genai#332] opened 2024-04-25 22:18 UTC
If you have a project referencing both the onnxruntime and the genai package, and if I try to build a windows app (WinAppSDK), it fails:
```xml
<PackageReference Include="Microsoft.ML.OnnxRuntime.DirectML" Version="1.17.3" />
<PackageReference Include="Microsoft.ML.OnnxRuntimeGenAI.DirectML" Version="0.2.0-rc4" />
```

```
1>C:\Users\alzollin\.nuget\packages\microsoft.windowsappsdk\1.5.240404000\buildTransitive\Microsoft.Build.Msix.Packaging.targets(1515,5): error APPX1101: Payload contains two or more files with the same destination path 'DirectML.dll'. Source files: 
1>C:\Users\alzollin\.nuget\packages\microsoft.windowsappsdk\1.5.240404000\buildTransitive\Microsoft.Build.Msix.Packaging.targets(1515,5): error APPX1101: C:\Users\alzollin\.nuget\packages\microsoft.ml.onnxruntimegenai.directml\0.2.0-rc4\runtimes\win-x64\native\DirectML.dll
1>C:\Users\alzollin\.nuget\packages\microsoft.windowsappsdk\1.5.240404000\buildTransitive\Microsoft.Build.Msix.Packaging.targets(1515,5): error APPX1101: C:\Users\alzollin\.nuget\packages\microsoft.ai.directml\1.13.1\bin\x64-win\DirectML.dll
1>C:\Users\alzollin\.nuget\packages\microsoft.windowsappsdk\1.5.240404000\buildTransitive\Microsoft.Build.Msix.Packaging.targets(1515,5): error APPX1101: Payload contains two or more files with the same destination path 'onnxruntime.dll'. Source files: 
1>C:\Users\alzollin\.nuget\packages\microsoft.windowsappsdk\1.5.240404000\buildTransitive\Microsoft.Build.Msix.Packaging.targets(1515,5): error APPX1101: C:\Users\alzollin\.nuget\packages\microsoft.ml.onnxruntimegenai.directml\0.2.0-rc4\runtimes\win-x64\native\onnxruntime.dll
1>C:\Users\alzollin\.nuget\packages\microsoft.windowsappsdk\1.5.240404000\buildTransitive\Microsoft.Build.Msix.Packaging.targets(1515,5): error APPX1101: C:\Users\alzollin\.nuget\packages\microsoft.ml.onnxruntime.directml\1.17.3\runtimes\win-x64\native\onnxruntime.dll
```

**Comment by azchohfi** [comment] 2024-04-25 22:19
A workaround is to remove one of them:
```xml
<PackageReference Include="Microsoft.ML.OnnxRuntime.DirectML" Version="1.17.3" PrivateAssets="contentfiles;analyzers" ExcludeAssets="build" />
```

**Comment by baijumeswani** [comment] 2024-04-29 17:29
Thanks for reporting this. We are trying to come up with a solution that will resolve this problem. We are probably going to target a solution for a future release (not 0.2.0).

**Comment by azchohfi** [comment] 2024-04-30 23:32
I see the PR is out. Is this still not for 0.2.0? I believe it would need cherry-picking, but maybe this is too much breaking of a change that you want it for later?

**Comment by baijumeswani** [comment] 2024-04-30 23:45
This would impact 0.2.0 dml variant if we cherry picked it since ort has changes not currently released in a stable nuget. We probably will not be adding it to 0.2.0.

Does the problem also manifest in a console application? I was not able to reproduce this there. Maybe it only happens with WinAppSDK?

**Comment by azchohfi** [comment] 2024-04-30 23:53
I see. No problem.
I believe it replicates in any packaged (MSIX) app, not necessarily WinAppSDK.

**Comment by natke** [comment] 2024-05-21 19:13
Closing this for now. We have an ongoing effort to resolve the inclusion of ONNXR Runtime nugets in this library

**Closed by natke** 2024-05-21 19:13 UTC
