### ISSUE TITLE
GeneratorParams should not throw an exception

### ISSUE THREAD

**Issue by skottmckay** [microsoft/onnxruntime-genai#453] opened 2024-05-14 08:17 UTC
>      throw JSON::unknown_value_error{};

Unknown parameters result in an exception being thrown, but the user of the API has no definition for the exception type so the best you can get is an 'unknown exception' error and no error info.

API needs to return an OgaResult if you wish to return error info for unknown parameter names.

**Comment by skottmckay** [comment] 2024-05-16 02:00
Slight clarification. It can throw at the lower level, but should be caught in genai code and returned from the C API as an OgaResult.

**Comment by baijumeswani** [comment] 2024-09-10 19:53
I could not reproduce this with the C API we currently have. The parsing of the config happens when we create the OgaModel. And the OgaModel creation returns an OgaResult.
Maybe it changed after you reported this error?

I'll close this issue for now.

**Closed by baijumeswani** 2024-09-10 19:53 UTC
Labels: enhancement
