### ISSUE TITLE
Phi3-mini-INT4 performance speedup with numpy 2.0 or above

### ISSUE THREAD

**Issue by bkaruman** [microsoft/onnxruntime-genai#899] opened 2024-09-18 17:09 UTC
Hi!

I am observing significant speedup in tokenization and prompt processing throughput with numpyv2 on Intel CPUs.
Can someone help understand how GenAI makes use of numpy during tokenization/prompt phase?

**Comment by natke** [comment] 2024-09-23 18:40
Hi @bkaruman, thanks for bringing to our attention - which Intel CPU are you running on?

**Comment by bkaruman** [comment] 2024-09-23 18:44
> Hi @bkaruman, thanks for bringing to our attention - which Intel CPU are you running on?

Intel Core Ultra Meteor Lake

**Comment by natke** [comment] 2024-09-23 18:59
Thanks. And the only difference is you upgraded to 0.4.0?

How long is the prompt you are running? (Or range of lengths)

**Comment by bkaruman** [comment] 2024-09-23 19:04
> Thanks. And the only difference is you upgraded to 0.4.0?
> Yes, here's the environment I use.
> ONNX RT (1.19.0) + ORT GEN(0.4.0) + numpy v2.0.0
   I have seen significant difference in perf running numpy 2.0 and numpy 1.24.4
> How long is the prompt you are running? (Or range of lengths)
I am running for prompt length = 1024, 2048 and generation length=1024,2048

**Comment by natke** [comment] 2024-10-07 05:57
Hi @bkaruman, we can't reproduce the speedup with numpy 2. Closing this issue for now. Please re-open if you continue to observe this behavior.

**Closed by natke** 2024-10-07 05:57 UTC
